  
# Javascript Node CircleCI 2.1 configuration file
#
#
#
version: 2.1
orbs:
  framer: cli-orb/framer@1.7.0
workflows:
  version: 2.1
  build-project:
    triggers:
      - schedule:
          cron: "0 8 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - framer/component-import:
          component-library-package: "test-design-demo"
          framer-project-path: "./"
          color-token-path: "./assets/colors.json"
          icon-path: "./svg"
  build-and-publish:
    jobs:
      - framer/build:
          framer-project-path: "./"
          filters:
            branches:
              only: master
      - framer/publish:
          framer-project-path: "./"
          framer-package-name: "Test Design Demo"
          requires:
            - framer/build
          filters:
            branches:
              only: master
